Document: tomotools
Title: Debian tomotools Manual
Author: <insert document author here>
Abstract: This manual describes what tomotools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tomotools/tomotools.sgml.gz

Format: postscript
Files: /usr/share/doc/tomotools/tomotools.ps.gz

Format: text
Files: /usr/share/doc/tomotools/tomotools.text.gz

Format: HTML
Index: /usr/share/doc/tomotools/html/index.html
Files: /usr/share/doc/tomotools/html/*.html
