#!/usr/bin/Rscript --slave --vanilla
#Needs R.utils. Install with these R commands:
#source("http://www.braju.com/R/hbLite.R")
#hbLite("R.utils")
#Needs latticeExtra. Install with the R command:
#install.packages(latticeExtra)
cmd_args <- commandArgs()
if (length(cmd_args)==6) file <- cmd_args[6] else file <- "rho03.mag"
if (length(cmd_args)==8) file <- cmd_args[8] else file <- "rho03.mag"
library(R.utils)
library(latticeExtra)
a <- read.table(file,fill=TRUE,col.names=c("x","z",
        "value_x"))
a <- a[-1,]
# PNG output
png(filename=sprintf("mag_aniso.png",file),width=1800,height=1200,
	res=300,type="cairo")
# or PDF
#pdf(file=sprintf("test_%s.pdf",file),width=6,height=4)
text = getwd()

colors		<- 	101
maxval 		<- 	max(max(a[c("value_x")]))
minval 		<- 	min(min(a[c("value_x")]))
scale 		<-	maxval-minval+1
jet.colors 	<- 	colorRampPalette(c("#00007F", "blue", "#007FFF", 
			"cyan", "#7FFF7F", "yellow", "#FF7F00", 
			"red", "#7F0000"))
scale           <-      0
minval          <-      3.5
maxval          <-      6.5
levels 		<- 	seq(minval-0.1*scale,maxval+0.1*scale,length=colors)
levels_short<-	seq(minval-0.1*scale,maxval+0.1*scale,length=12)
plot.new()
trellis.par.set(cex.axes=1)
b=read.table("../grid/elem.dat",nrow=1)
nknot = b[[1]]
ntyp = b[[2]]
knots = read.table("../grid/elem.dat",skip=1+ntyp,nrow=nknot)
c=read.table("../grid/elec.dat",skip=1)
# POTENTIAL PLOT
p1 <- levelplot	(value_x ~ x * z, a,
		at=levels,col.regions=jet.colors(colors),
		main=expression(paste("magnitude in [",Omega,"m]")),
		ylab="depth in [m]",
		xlab="lateral coordinate in [m]",
		aspect = "iso",
		colorkey = list(space="right",tick.number=1,height=1,
		width=1.5,
		labels = list(at = levels_short,cex=1,rot=0,
		lab = sprintf("%5.1f",levels_short))),
		panel=function(...){
                                panel.levelplot(...)
                                panel.points(knots[knots[c[[1]],1],2],knots[knots[c[[1]],1],3],pch=19,col="black",cex=.5)
})
update(c(p1),scales=list(cex.main=2),layout=c(1,1),xlim=c(0,.3),
        ylim=c(-.3,0))
#text(0.5,0.64,labels="x",cex=0.7)
#text(0.5,0.1,labels="z",cex=0.7)
dev.off()

