#!/bin/bash

tools="plotCRTmod_batch.m epstopdf matlab mogrify";

echo "checking for tools"
forcecheck(){
	Ret_val=`which $1`
	if [ -z "$Ret_val" ];then
		echo "$1 not in search path.. searching $HOME..."
		Ret_val=`find $HOME -name "$1" -print`
		if [ -z "$arg" ];then
			exit
		fi
	fi
	return
}

i=1;
for x in $tools;do
	forcecheck $x
	case "$i" in
		1)
			plotmod=$Ret_val
		;;
		2)
			epsp=$Ret_val
		;;
		3)
			mtlb=$Ret_val
		;;
		4)
			mogri=$Ret_val
		;;
		*)
			echo "not possible"
			exit
		;;
	esac
	i=$[$i+1];
done

awk '{if (NR==2){print}}' crtomo.cfg > tmp.meshname
awk '{if (NR==3){print}}' crtomo.cfg > tmp.elecname

if [ -e "tmp.fenster" ];then
    fenster=`cat tmp.fenster`
else
    fenster=$1
fi
echo $fenster > tmp.fenster

if [ -e "tmp.crange" ];then
    c1=`awk '{print$1}' tmp.crange`
    c2=`awk '{print$2}' tmp.crange`
else
    c1=`pwd|awk '/2_decades/{printf("%.1f\t%.1f",1.0,3.0)}'` 
    c2=`pwd|awk '/3_decades/{printf("%.1f\t%.1f",0.5,3.5)}'` 
    c3=`pwd|awk '/4_decades/{printf("%.1f\t%.1f",0.0,4.0)}'` 
fi

echo range check: $c1 $c2 $c3 $2
echo $c1 $c2 $c3 $2 > tmp.crange

if [ -e inv.lastmod ];then
    echo found inv.lastmod
else
    echo no inv.lastmod present..
    exit
fi

$mtlb < $plotmod >& /dev/null

tmp=`cat inv.lastmod`
myeps=`basename $tmp`'.eps'
mypdf=`basename $myeps '.eps'|tr '.' '_'`'.pdf'
echo image conversion... $myeps $mypdf
$epsp $myeps -o=$mypdf >& /dev/null
echo "done $1"

pdfcr=`which pdfcrop`
forcecheck $pdfcr
$pdfcr --margins 1 --hires $mypdf cropped.pdf >& /dev/null
