#!/bin/bash

tools="Griev";
ctr=tmp.griev_ctr
echo "checking for tools"
forcecheck(){
	Ret_val=`which $1`
	if [ -z "$Ret_val" ];then
		echo "$1 not in search path.. searching $HOME..."
		Ret_val=`find $HOME -name "$1" -print`
		if [ -z "$arg" ];then
			exit
		fi
	fi
	return
}

i=1;
for x in $tools;do
	forcecheck $x
	case "$i" in
		1)
			griev=$Ret_val
		;;
		*)
			echo "not possible"
			exit
		;;
	esac
	i=$[$i+1];
done
if [ -e crtomo.cfg ];then
    echo found crtomo.cfg
    elem=`awk '{if (NR==2){print}}' crtomo.cfg`
    elec=`awk '{if (NR==3){print}}' crtomo.cfg`
else
    if [ -e elem.dat ];then
	elem='elem.dat'; 
    else
	echo there is no crtomo.cfg nor elem.dat.. exiting
	exit
    fi
    if [ -e elec.dat ];then
	elec='elec.dat'; 
    else
	echo there is no crtomo.cfg nor elec.dat.. exiting
	exit
    fi
fi


if [ -n $1 ];then 
    mod=$1;
else 
    mod='';
fi

if [ -z $mod ];then
    if [ -e inv.lastmod ];then
	echo found inv.lastmod
	mag=`cat inv.lastmod`
	mod=$mag
	ismag=`echo $mag|grep mag`
#	if [ -n $ismag ];then 
#	    mod=${mag%mag}modl;
#	    awk '{if(NR==1){print}else{print $3,0}}' $mag > $mod
#	fi
    else
	exit
    fi
fi

if [ -e "tmp.fenster" ];then
    titel=`cat tmp.fenster`
else
    titel=$2
fi

if [ -z "$titel" ];then
    titel='CRTomo result';
fi

if [ -e "tmp.cbarn" ];then
    cbarn=`cat tmp.cbarn`
else
    cbarn=$3
fi

if [ -z "$cbarn" ];then 
    cbarn='Units';
fi

if [ -e "tmp.crange" ];then
    maxrho=`awk '{print $2}' tmp.crange`
    minrho=`awk '{print $1}' tmp.crange`
fi

# default plot labels
#cls_default_plot_labels:{
#	plot_x_label = "xLabel from Config";
#	plot_y_label = "ylabel from Config";
#	plot_color_label = "CB F C";
#	plot_title = "Unglaublicher Titel aus Config File";
#};

mypdf=`basename $mod|tr '.' '_'`'.pdf'

echo 'action_open = true;' > $ctr
echo 'open_file_elem = "'$elem'";' >> $ctr
echo 'open_file_elec = "'$elec'";' >> $ctr
echo 'exit = 1;' >> $ctr
#echo 'show_par_set = 0;' >> $ctr
#echo 'show_par_set = 0;' >> $ctr
echo 'nr_par = 1;' >> $ctr
if [ -n $ismag ];then
    echo 'par_1_format_rho = 0;' >> $ctr
else
    echo 'par_1_format_rho = 1;' >> $ctr
fi
echo 'par_1_file = "'$mod'";' >> $ctr
if [ -n "$minrho" ];then
    echo "par_1_min_rho = $minrho;" >> $ctr
    echo "par_1_max_rho = $maxrho;" >> $ctr
fi
echo 'par_1_use_latex_interpreter = 0;' >> $ctr
echo 'par_1_xlabel = "X /m";' >> $ctr
echo 'par_1_ylabel = "Z /m";' >> $ctr
echo 'par_1_cblabel = "'$cbarn'";' >> $ctr
echo 'par_1_title = "'$titel'";' >> $ctr
echo 'par_1_print_file = "'$mypdf'";' >> $ctr
echo 'par_1_print = 1;' >> $ctr

$griev -u $ctr >& $ctr.log