#!/bin/bash

tools="Griev";

echo "checking for tools"
forcecheck(){
	Ret_val=`which $1`
	if [ -z "$Ret_val" ];then
		echo "$1 not in search path.. searching $HOME..."
		Ret_val=`find $HOME -name "$1" -print`
		if [ -z "$arg" ];then
			exit
		fi
	fi
	return
}

i=1;
for x in $tools;do
	forcecheck $x
	case "$i" in
		1)
			griev=$Ret_val
		;;
		*)
			echo "not possible"
			exit
		;;
	esac
	i=$[$i+1];
done
if [ -e crtomo.cfg ];then
    echo found crtomo.cfg
    elem=`awk '{if (NR==2){print}}' crtomo.cfg`
    elec=`awk '{if (NR==3){print}}' crtomo.cfg`
else
    if [ -e elem.dat ];then
	elem='elem.dat'; 
    else
	echo there is no crtomo.cfg nor elem.dat.. exiting
	exit
    fi
    if [ -e elec.dat ];then
	elec='elec.dat'; 
    else
	echo there is no crtomo.cfg nor elec.dat.. exiting
	exit
    fi
fi


if [ -n $1 ];then 
    mod=$1;
else 
    mod='';
fi

if [ -z $mod ];then
    if [ -e inv.lastmod ];then
	echo found inv.lastmod
	mag=`cat inv.lastmod`
	mod=$mag
	ismag=`echo $mag|grep mag`
#	if [ -n $ismag ];then 
#	    mod=${mag%mag}modl;
#	    awk '{if(NR==1){print}else{print $3,0}}' $mag > $mod
#	fi
    else
	exit
    fi
fi

if [ -e "tmp.fenster" ];then
    titel=`cat tmp.fenster`
else
    titel=$2
fi

if [ -z $titel ];then titel='CRTomo result';fi

if [ -e "tmp.cbarn" ];then
    cbarn=`cat tmp.cbarn`
else
    cbarn=$3
fi
echo $cbarn
if [ -z "$cbarn" ];then cbarn='Units';fi


griev_std="-i -e $elem -t $elec"
griev_std=$griev_std`echo '-a "'$titel'"'`
griev_std=`echo $griev_std' -s "'$cbarn'" -k "X /m" -q "Y /m"'`
 
mypdf=`basename $mod|tr '.' '_'`'.pdf'

if [ -n $ismag ];then
    griev_std=$griev_std' -y 1 -m '$mod' -p -o '$mypdf
    echo $griev_std
    $griev $griev_std
else
    echo $griev_std
    $griev $griev_std -r $mod -j -p -o $mypdf
fi